// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pySDyPPApi.Data;

#nullable disable

namespace pySDyPPApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251209181852_AddNombreToPruebas")]
    partial class AddNombreToPruebas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("pySDyPPApi.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDiabetes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.ToTable("pacientes");

                    b.HasData(
                        new
                        {
                            PacienteId = 1,
                            Apellidos = "Arróniz Saiz",
                            Edad = 20,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            Nombre = "María",
                            Telefono = "123456789",
                            TipoDiabetes = "TipoI"
                        },
                        new
                        {
                            PacienteId = 2,
                            Apellidos = "Deras Ortiz",
                            Edad = 22,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            Nombre = "Nazaret",
                            Telefono = "987654321",
                            TipoDiabetes = "TipoII"
                        },
                        new
                        {
                            PacienteId = 3,
                            Apellidos = "García López",
                            Edad = 45,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            Nombre = "Javier",
                            Telefono = "601835924",
                            TipoDiabetes = "TipoII"
                        },
                        new
                        {
                            PacienteId = 4,
                            Apellidos = "Martínez Ruíz",
                            Edad = 31,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            Nombre = "Elena",
                            Telefono = "678102934",
                            TipoDiabetes = "TipoI"
                        },
                        new
                        {
                            PacienteId = 5,
                            Apellidos = "Sánchez Pérez",
                            Edad = 60,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            Nombre = "Carlos",
                            Telefono = "722560813",
                            TipoDiabetes = "TipoII"
                        },
                        new
                        {
                            PacienteId = 6,
                            Apellidos = "Fernández Soto",
                            Edad = 14,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Femenino",
                            Nombre = "Laura",
                            Telefono = "640917285",
                            TipoDiabetes = "TipoI"
                        },
                        new
                        {
                            PacienteId = 7,
                            Apellidos = "Hernández Gil",
                            Edad = 55,
                            FechaNacimiento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "Masculino",
                            Nombre = "Miguel",
                            Telefono = "699345102",
                            TipoDiabetes = "TipoI"
                        });
                });

            modelBuilder.Entity("pySDyPPApi.Models.Prueba", b =>
                {
                    b.Property<int>("PruebaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Realizada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SiguienteRealizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPrueba")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("PruebaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("pruebas");

                    b.HasDiscriminator<string>("TipoPrueba").HasValue("Prueba");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("pySDyPPApi.Models.Analitica", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<bool>("Hba1")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Analitica");

                    b.HasData(
                        new
                        {
                            PruebaId = 1,
                            Estado = "Realizada",
                            FechaRealizacion = new DateTime(2025, 11, 24, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6918),
                            Nombre = "Analitica",
                            Observaciones = "Perfil lipídico ok.",
                            PacienteId = 1,
                            Realizada = true,
                            Resultado = "Normal",
                            SiguienteRealizacion = new DateTime(2026, 6, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6968),
                            Hba1 = true
                        },
                        new
                        {
                            PruebaId = 2,
                            Estado = "Pendiente",
                            FechaRealizacion = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Analitica",
                            Observaciones = "Programar cita.",
                            PacienteId = 3,
                            Realizada = false,
                            Resultado = "Pendiente",
                            SiguienteRealizacion = new DateTime(2026, 12, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6973),
                            Hba1 = false
                        });
                });

            modelBuilder.Entity("pySDyPPApi.Models.Constantes", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<float>("Altura")
                        .HasColumnType("REAL");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<float>("TensionArterial")
                        .HasColumnType("REAL");

                    b.Property<float>("glucemiaCapilar")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Constantes");

                    b.HasData(
                        new
                        {
                            PruebaId = 3,
                            Estado = "Realizada",
                            FechaRealizacion = new DateTime(2025, 12, 4, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6989),
                            Nombre = "Constantes",
                            Observaciones = "Tensión y glucemia estables.",
                            PacienteId = 1,
                            Realizada = true,
                            Resultado = "Óptimo",
                            SiguienteRealizacion = new DateTime(2026, 3, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6990),
                            Altura = 1.7f,
                            Peso = 65.5f,
                            TensionArterial = 120.8f,
                            glucemiaCapilar = 105f
                        },
                        new
                        {
                            PruebaId = 4,
                            Estado = "Realizada",
                            FechaRealizacion = new DateTime(2025, 12, 8, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6994),
                            Nombre = "Constantes",
                            Observaciones = "Tensión ligeramente alta.",
                            PacienteId = 3,
                            Realizada = true,
                            Resultado = "Límite",
                            SiguienteRealizacion = new DateTime(2026, 3, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(6995),
                            Altura = 1.82f,
                            Peso = 88f,
                            TensionArterial = 140.95f,
                            glucemiaCapilar = 135f
                        });
                });

            modelBuilder.Entity("pySDyPPApi.Models.Electrocardiograma", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.HasDiscriminator().HasValue("Electrocardiograma");

                    b.HasData(
                        new
                        {
                            PruebaId = 7,
                            Estado = "Realizada",
                            FechaRealizacion = new DateTime(2025, 11, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(7027),
                            Nombre = "Electrocardiograma",
                            Observaciones = "Sin alteraciones relevantes.",
                            PacienteId = 3,
                            Realizada = true,
                            Resultado = "Normal",
                            SiguienteRealizacion = new DateTime(2026, 12, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(7028)
                        });
                });

            modelBuilder.Entity("pySDyPPApi.Models.ITB", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.HasDiscriminator().HasValue("ITB");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Preguntas", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<string>("ActividadFisica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alcohol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Drogas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fumar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaMedicacionCorectamente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Preguntas");

                    b.HasData(
                        new
                        {
                            PruebaId = 5,
                            Estado = "Realizada",
                            FechaRealizacion = new DateTime(2025, 11, 19, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(7010),
                            Nombre = "Preguntas",
                            Observaciones = "Estilo de vida activo.",
                            PacienteId = 1,
                            Realizada = true,
                            Resultado = "Bajo riesgo",
                            SiguienteRealizacion = new DateTime(2026, 12, 9, 19, 18, 52, 456, DateTimeKind.Local).AddTicks(7011),
                            ActividadFisica = "Regular",
                            Alcohol = "Ocasional",
                            Drogas = "No",
                            Fumar = "No",
                            TomaMedicacionCorectamente = "Sí"
                        });
                });

            modelBuilder.Entity("pySDyPPApi.Models.Retinografia", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<bool>("AlteracionesTipoII")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Retinografia");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Prueba", b =>
                {
                    b.HasOne("pySDyPPApi.Models.Paciente", "Paciente")
                        .WithMany("PruebasRealizadas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Paciente", b =>
                {
                    b.Navigation("PruebasRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
