// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pySDyPPApi.Data;

#nullable disable

namespace pySDyPPApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("pySDyPPApi.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Edad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDiabetes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PacienteId");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Prueba", b =>
                {
                    b.Property<int>("PruebaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRealizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Realizada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SiguienteRealizacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPrueba")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("PruebaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("pruebas");

                    b.HasDiscriminator<string>("TipoPrueba").HasValue("Prueba");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("pySDyPPApi.Models.Analitica", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<bool>("Hba1")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Analitica");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Constantes", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<float>("Altura")
                        .HasColumnType("REAL");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<float>("TensionArterial")
                        .HasColumnType("REAL");

                    b.Property<float>("glucemiaCapilar")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Constantes");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Electrocardiograma", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.HasDiscriminator().HasValue("Electrocardiograma");
                });

            modelBuilder.Entity("pySDyPPApi.Models.ITB", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.HasDiscriminator().HasValue("ITB");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Preguntas", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<string>("ActividadFisica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alcohol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Drogas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fumar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TomaMedicacionCorectamente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Preguntas");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Retinografia", b =>
                {
                    b.HasBaseType("pySDyPPApi.Models.Prueba");

                    b.Property<bool>("AlteracionesTipoII")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Retinografia");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Prueba", b =>
                {
                    b.HasOne("pySDyPPApi.Models.Paciente", "Paciente")
                        .WithMany("PruebasRealizadas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("pySDyPPApi.Models.Paciente", b =>
                {
                    b.Navigation("PruebasRealizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
